project:
  type: website
  output-dir: docs
website:
  title: "Simon Christensen"
  navbar:
    title: Home
    right:
      - text: Final Project
        href: math-437-project-template.qmd
format:
  html:
    backgroundcolor: "#e6f2ff"
    fontcolor: "darkblue"
    linkcolor: "black"
    mainfont: "serif"
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



